import 'package:persuit/domain/entities/holding.dart';
import 'package:persuit/domain/entities/stock.dart';

const watchlistShares = [
  Stock(
    name: 'INFY',
    latestPrices: 1766.55,
    dayChange: 48.05,
    percentChange: 2.65,
    isUptrend: false,
  ),
  Stock(
    name: 'ONGC',
    latestPrices: 171.20,
    dayChange: 0.30,
    percentChange: 0.18,
    isUptrend: true,
  ),
  Stock(
    name: 'TCS',
    latestPrices: 3696.40,
    dayChange: 10.75,
    percentChange: 0.29,
    isUptrend: true,
  ),
  Stock(
    name: 'KPITTECH',
    latestPrices: 598.85,
    dayChange: 16.45,
    percentChange: 2.67,
    isUptrend: false,
  ),
  Stock(
    name: 'QUICKHEAL',
    latestPrices: 201.35,
    dayChange: 3.30,
    percentChange: 1.67,
    isUptrend: true,
  ),
  Stock(
    name: 'WIPRO',
    latestPrices: 571.10,
    dayChange: 12.55,
    percentChange: 2.15,
    isUptrend: false,
  ),
  Stock(
    name: 'M&M',
    latestPrices: 856.85,
    dayChange: 0.55,
    percentChange: 0.06,
    isUptrend: false,
  ),
  Stock(
    name: 'RELIANCE',
    latestPrices: 2610.20,
    dayChange: 5.45,
    percentChange: 0.21,
    isUptrend: false,
  ),
  Stock(
    name: 'HINDUNILVR',
    latestPrices: 2163.05,
    dayChange: 20.00,
    percentChange: 0.91,
    isUptrend: false,
  ),
];

const holdings = [
  Holding(
    quantity: 7,
    avgPrice: 645.20,
    overallProfitPercentage: 17.47,
    overallProfitPrice: 788.90,
    totalInvested: 4516.40,
    isInProfit: true,
    stock: Stock(
      name: 'BHARTIARTL',
      latestPrices: 757.90,
      dayChange: 4.50,
      percentChange: 0.56,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 5,
    avgPrice: 325.71,
    overallProfitPercentage: 0.89,
    overallProfitPrice: 14.45,
    totalInvested: 1628.55,
    isInProfit: true,
    stock: Stock(
      name: 'EVEREADY',
      latestPrices: 328.60,
      dayChange: 1.66,
      percentChange: 1.66,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 7,
    avgPrice: 1484.77,
    overallProfitPercentage: 0.77,
    overallProfitPrice: 80.00,
    totalInvested: 10393.40,
    isInProfit: true,
    stock: Stock(
      name: 'HDFCBANK',
      latestPrices: 2163.05,
      dayChange: 0.92,
      percentChange: 0.92,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 3,
    avgPrice: 1613.43,
    overallProfitPercentage: 9.50,
    overallProfitPrice: 459.65,
    totalInvested: 4840.30,
    isInProfit: true,
    stock: Stock(
      name: 'INFY',
      latestPrices: 1766.65,
      dayChange: 2.67,
      percentChange: 2.67,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 10,
    avgPrice: 216.28,
    overallProfitPercentage: 23.59,
    overallProfitPrice: 510.25,
    totalInvested: 2162.75,
    isInProfit: true,
    stock: Stock(
      name: 'ITC',
      latestPrices: 267.30,
      dayChange: 0.19,
      percentChange: 0.19,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 2,
    avgPrice: 3532.75,
    overallProfitPercentage: 21.08,
    overallProfitPrice: 1489.30,
    totalInvested: 7065.50,
    isInProfit: false,
    stock: Stock(
      name: 'JUBLFOOD',
      latestPrices: 2788.10,
      dayChange: 0.19,
      percentChange: 0.19,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 2,
    avgPrice: 3532.75,
    overallProfitPercentage: 21.08,
    overallProfitPrice: 1489.30,
    totalInvested: 7065.50,
    isInProfit: false,
    stock: Stock(
      name: 'JUBLFOOD',
      latestPrices: 2788.10,
      dayChange: 0.19,
      percentChange: 0.19,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 10,
    avgPrice: 300.10,
    overallProfitPercentage: 99.57,
    overallProfitPrice: 2988,
    totalInvested: 3001,
    isInProfit: true,
    stock: Stock(
      name: 'KPITTECH',
      latestPrices: 598.90,
      dayChange: 2.68,
      percentChange: 2.68,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 5,
    avgPrice: 840.88,
    overallProfitPercentage: 1.90,
    overallProfitPrice: 79.85,
    totalInvested: 4204.40,
    isInProfit: true,
    stock: Stock(
      name: 'M&M',
      latestPrices: 856.85,
      dayChange: 0.27,
      percentChange: 0.27,
      isUptrend: false,
    ),
  ),
  Holding(
    quantity: 20,
    avgPrice: 176.71,
    overallProfitPercentage: 60.12,
    overallProfitPrice: 2124.85,
    totalInvested: 3534.15,
    isInProfit: true,
    stock: Stock(
      name: 'TATAPOWER',
      latestPrices: 282.95,
      dayChange: 1.73,
      percentChange: 1.73,
      isUptrend: true,
    ),
  ),
];
